### ISSUE TITLE
Read tickets from file?

### ISSUE THREAD

**Issue by carljv** [marythought/tickets#1]
Very cool! I know very little Go, but was able to follow the source easily.

But what if I buy new tickets after I build the program, and am too lazy to re-compile? Could I keep my tickets listed in a text-file and have the program read it in when I want to check for a winner? Maybe using [Scanner](https://golang.org/pkg/bufio/#Scanner)?

**Comment by marythought** [comment]
Oooh clever! Ok I'll work on text source reading at lunch.

By the way you can't buy these tickets, you have to schmooze with vendors.
😂

**Comment by marythought** [comment]
completed in https://github.com/marythought/tickets/pull/2

**Comment by marythought** [comment]
needs thorough testing but I think this works!
